sudo: false

language: ruby
rvm:
- 2.2

# it will be moved to specific script soon
install: gem install jekyll jekyll-paginate html-proofer
script: jekyll build && htmlproofer ./_site

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master 		 # master
  - gh-pages     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of