sudo: false

language: ruby
rvm:
- 2.1

# it will be moved to specific script soon
install: gem install jekyll html-proofer
script: jekyll build #this isn't working yet  && htmlproof ./_site

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master 		 # master
  - gh-pages     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of