permalink: /:categories/:year/:month/:day/:title 
highlighter: pygments

#Personcal Setting
title : Code·Play·Live
tagline: Site Tagline
author :
  name : Ekalak Mint
  email : mint (dot) com (at) gmail (dot) com
  github : anonymint
  twitter : anonymint
  feedburner : feedname

paginate: 5

#Markdown
markdown: kramdown
markdown_ext: markdown,md