gems :
  - jekyll-paginate

permalink: /:categories/:year/:month/:day/:title.html

#Personcal Setting
title : Code·Play·Live
tagline: Site Tagline
author :
  name : Ekalak Mint
  email : mint (dot) com (at) gmail (dot) com
  github : anonymint
  twitter : anonymint
  feedburner : feedname

paginate: 15

#Markdown
markdown_ext: markdown,md
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge